export const WINDOW_FOCUSED = 'WINDOW_FOCUSED';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const FETCH_FILES_REQUEST = 'FETCH_FILES_REQUEST';
export const FETCH_FILES_FAILURE = 'FETCH_FILES_FAILURE';
export const FETCH_FILES_SUCCESS = 'FETCH_FILES_SUCCESS';

export const FILE_SELECTED = 'FILE_SELECTED';
export const FILE_DESELECTED = 'FILE_DESELECTED';
export const FILE_DESELECTED_ALL = 'FILE_DESELECTED_ALL';
export const FILE_GROUP_SELECTED = 'FILE_GROUP_SELECTED';
export const FILE_DOWNLOAD_REQUEST = 'FILE_DOWNLOAD_REQUEST';
export const FILE_TRANSFER_REQUEST = 'FILE_TRANSFER_REQUEST';
export const DIRECTORY_TRANSFER_REQUEST = 'DIRECTORY_TRANSFER_REQUEST';
