export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const FETCH_FILES_REQUEST = 'FETCH_FILES_REQUEST';
export const FETCH_FILES_FAILURE = 'FETCH_FILES_FAILURE';
export const FETCH_FILES_SUCCESS = 'FETCH_FILES_SUCCESS';

export const FILE_SELECTED = 'FILE_SELECTED';
export const FILE_DESELECTED = 'FILE_DESELECTED';
